apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris-site
        image: ociotec/tetris